---

- name: ensure common system packages are present
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - build-essential
    - git
    - htop
    - python-dev
    - python-pip
    - python-virtualenv
    - tree
    - vim
